language: node_js
node_js:
- 15
branches:
  only:
  - master
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "www.legraverend.fr"
  region: "us-east-1"
  skip_cleanup: true
  acl: public_read
  local_dir: dist
notifications:
  email: false
